info help:  ## Shows the commands + comments below
	@grep -E '^([a-zA-Z_-])+[^:]+:.*?## (.*)$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Cleans autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage
	pre-commit clean

check checks: ## Runs pre-commit hooks (cleanups, auto-reformats, ...)
	pre-commit run -a

test tests: ## Runs not-slow tests using pytest
	pytest -k "not slow"

test-all tests-all: ## Runs all tests (including slow ones)
	pytest
